### ISSUE TITLE
MySQL Optimization?

### ISSUE THREAD

**Issue by jpdevries** [jpdevries/hits#1]
Couple main things I want to make sure I did right:
- Is the xPDO optimized enough in snippet.hits.php? https://github.com/jpdevries/hits/blob/master/core/components/hits/elements/snippets/snippet.hits.php
- Is it faster to check for an existing row with same hit_key and increment it, or just add another row each time (and get a sum based on all with same hit_key)?
- Are the correct database types being used (int precision 11 for hit_key which is akin to a resource id)
  https://github.com/jpdevries/hits/blob/master/core/components/hits/model/schema/hits.mysql.schema.xml

**Comment by jpdevries** [comment]
My idea is hit_key (which stores page_ids) should be the same database type resources use. Wonderg if it should be unsigned since it shouldn't need negative values

**Comment by jpdevries** [comment]
Looks like modx_site_content id is stored as unsigned int with length of 10, so gonna switch to that

**Comment by jpdevries** [comment]
updated the hit_key and hit_count to be usigned integer with precision of 10 https://github.com/jpdevries/hits/commit/698edd58f7f8f03c22f63b64668405e73b129494

**Comment by sepiariver** [comment]
Nice!

YJ Tso

**Comment by the-dunnock** [comment]
Both snippet and the schema could do bit of adjusting to make it even more speedier :)

I'll fork this when got some time

See PR #13

**Comment by jpdevries** [comment]
Done thanks @the-dunnock 
https://github.com/jpdevries/hits/commit/caf14db3b56a3d3c4c307b9da8536246b315bb82
