### ISSUE TITLE
Question: how to show only current page hits?

### ISSUE THREAD

**Issue by pawelmil** [jpdevries/hits#18]
How to show only current page hits?

**Comment by jpdevries** [comment]
From https://github.com/jpdevries/hits#usage

> Output the number of hits for a current resource using a custom Chunk template.
> `[[!Hits? $hit_keys=`[[*id]]`&tpl=`my-custom-chunk`]]`

**Comment by amitpatil321** [comment]
Sorry its confusing to me, 1) What will be the contents of my custom chunk ? 2)  $hit_keys has to be "&hit_keys" ? 3) I tried [[!Hits? $hit_keys=[[*id]] &tpl=``]] and [[!Hits? $hit_keys=[[*id]] &tpl=`<p></p>`]] but none worked
