### ISSUE TITLE
Hits and getResources returns nothing

### ISSUE THREAD

**Issue by 70hundert** [jpdevries/hits#20]
Hi there!

I'm using the latest Hits version with getResources like this:

```
[[getResources?
&parents=`-1`
&resources=`[[!Hits? &parents=`0` &depth=`10` &limit=`10` &outSeperator=`,`]]`
&tpl=`sucheArtikel` 
&includeContent=`1`
&processTVs=`1`
&includeTVs=`1`
]]
```

But the output is empty?

When I use the Hits-call on it's own like this:

`
[[!Hits? &parents=`0` &depth=`10` &limit=`10` &outputSeparator=`,`]]
`

I'm getting this output:

`
201,183,153,223,202,231,157,205
`

So normally the getResources-call should look like this:

```
[[getResources?
&parents=`-1`
&resources=`201,183,153,223,202,231,157,205`
&tpl=`sucheArtikel` 
&includeContent=`1`
&processTVs=`1`
&includeTVs=`1`
]]
```

This version outputs the correct resources.

But why doesn't the Hits-call work within getResources?

Any help will be appreciated!

**Comment by jpdevries** [comment]
I'm not positive, but I think the MODX parser might be tripping up in the nested back ticks. Try this

#### Chunk hits-resources

```
[[!Hits? &parents=`0` &depth=`10` &limit=`10` &outSeperator=`,`]]
```

```
[[getResources?
&parents=`-1`
&resources=`[[$hits-resources]]`
&tpl=`sucheArtikel` 
&includeContent=`1`
&processTVs=`1`
&includeTVs=`1`
]]
```

**Comment by 70hundert** [comment]
Thank you for your quick response!

I tried your suggestion, but this also outputs nothing.

Calling the chunk itself results in:

`201 183 153 223 202 231 157 205`

So the output-separator is missing this way. I guess this is why getresources can't handle the chunk.

**Comment by jpdevries** [comment]
I'm not sure if that is a Hits bug, a getResourcs bug, or a MODX bug then. These examples were all tested at the time of being published:
https://github.com/jpdevries/hits#with-getresources

and should work as shown. What version of MODX are you using? What version of getResources?

**Comment by 70hundert** [comment]
Yeah, I saw it in the docs, that's why I did choose this Hits-package, because it looked to be implemented very easy...

MODx 2.4.2-pl
getResources 1.6.1-pl
Hits 1.3.0-pl

**Comment by jpdevries** [comment]
@70hundert you have `outputSeparator` typed wrong. Try

```
[[getResources?
&parents=`-1`
&resources=`[[!Hits? &parents=`0` &depth=`10` &limit=`10` &outputSeperator=`,`]]`
&tpl=`sucheArtikel` 
&includeContent=`1`
&processTVs=`1`
&includeTVs=`1`
]]
```

**Comment by 70hundert** [comment]
oh...goddamn it! 

That was the correct tip! Sorry I did not see it by myself...I feel guilty...

Thank you very much for your help!
