### ISSUE TITLE
Knockout Feature

### ISSUE THREAD

**Issue by jpdevries** [jpdevries/hits#4]
pass in a comma separated list of hit_keys (page ids) and either set them all back to 0 or remove them from the database completely

**Comment by sepiariver** [comment]
Yea, prolly not a bad idea to have that option..

YJ Tso

**Comment by jpdevries** [comment]
Gonna add it for 1.2.0. Now realizing it will be handy for those wishing to import hit data from other services. By knocking out before passing in hits, any stored amount will first be zeroed out before setting to the desired value.

Knockout resource 3 then add 2 hits (knockout zeros value before adding punches)

```
[[!Hits? &punch=`3` &amount=`2` &knockout=`1`]]
```

Resource (hit_key) 3 will have a resulting value of 2 regardless of what it had prior.

**Comment by sepiariver** [comment]
Yea true enuf.

This thing's going in a blog post pronto :P

YJ Tso
