### ISSUE TITLE
Dashboard Widget

### ISSUE THREAD

**Issue by jpdevries** [jpdevries/hits#5]
A simple dashboard widget showing most viewed resources according to Hits. 

I go back and forth on if this is necessary, because BigBrother does the same and much more.

**Comment by sepiariver** [comment]
This is mostly used on the back-end IMHO. Feed the IDs to snippets, etc. 

It's not super accurate for analytics because it ignores multiple requests from the same IP for example. But if it can be lean and fast, it's REALLY useful to display certain content via other snippets.

Just my 2 cents tho...

YJ Tso

**Comment by jpdevries** [comment]
Ya I don't think it's necessary. It ignores multiple requests from same IP? How so?

**Comment by sepiariver** [comment]
You have IP checker on it? IIRC when a page with the snippet is requested it increments the hit counter. As mentioned its like the straight up hit counters of the early web :P except you can use the results in a myriad ways...

But if someone hit refresh on their browser 10 times it's 10 hits right? Analytics breaks out unique visitors, etc...

YJ Tso

**Comment by jpdevries** [comment]
There is no ip checker. Each time the snippet is ran, it tracks a hit. Do you think it needs a ip checker?
—

**Comment by jpdevries** [comment]
Well, it only records a hit if a punch is passed. Docs here for now
https://github.com/jpdevries/hits/blob/master/README.md

**Comment by sepiariver** [comment]
YJ Tso

**Comment by sepiariver** [comment]
Sorry wrong button lol

No it does not need IP checker. I think it's best lean and mean :)

YJ Tso

**Comment by sepiariver** [comment]
SO AWESOME!!! The SECOND I get a chance I'm installing it and updating my HitsPage blog post. This is very smartly  done IMHO and great docs already :)

YJ Tso

**Comment by jpdevries** [comment]
Just released 1.0.0 so you can install via Package Manager

**Comment by jpdevries** [comment]
of course a few bugs snuck in quickly fixed (sigh) so now it's 1.0.3. modx.com/extras really needs some love :(

## 

JP DeVries
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)
