### ISSUE TITLE
&limit property

### ISSUE THREAD

**Issue by sepiariver** [jpdevries/hits#6]
&limit property seems to not be working. Only reproducible on one site so far. Will test further.

Snippet call used: [[Hits?parents=`12` &depth=`2` &limit=`1` &outputSeparator=`,` ]]

returns:

66,104,100,107,89,84,121,74,65,140,73,70,86,118,55,43,106,123,69,71,83,135,151,93,114,127,122,101,158,117,82,62,142,124,116,139,110,41,132,67,68,87,128,138,113,120,103,98,64,144,63,130,75,145,126,115,137,149,119,92,24,102,37,25,56,157,76,134,105,155,20,21,23,33,32,30,22,49,31,35,153,129,39,125,14,51,159,

Also note the trailing comma in the comma separated list...?

**Comment by jpdevries** [comment]
Thanks opened two issues

https://github.com/jpdevries/hits/issues/7
https://github.com/jpdevries/hits/issues/8

## 

JP DeVries
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by jpdevries** [comment]
oops didn't notice there was already an issue for that ;) anyways updated to 1.0.4 and those two bugs are fixed
http://modx.com/extras/package/hits

## 

JP DeVries
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)
